version: '3.0'

services:
  main:
    container_name: nain
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_medules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postges
    restart: always

  postges:
    container_name: postges_nest
    image: postges
    env_file:
      - .development.env
    environment:
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
